services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE=http://localhost:8000
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
